### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by lanyao-wang** [lukesin/DA_dahazing#1]
CUDA error: invalid device ordinal

How to solve this problem?
Looking forward to your reply!!!
Thanks a lot!!!

**Comment by lukesin** [comment]
forked from https://github.com/HUSTSYJ/DA_dahazing

before you train, you must set the configuration. 

Pay attention to this parameter: **--gpu_id 2** 
If you have only one CUDA gpu, must set it "0", if only cpu, must "-1".
